
# Testing how to manually run Github Actions

# Source of this sample yml
# https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch

# NOTE: When using checkout action version 2, then action will warn about debracated Node.js
#       https://github.com/marketplace/actions/checkout?version=v4.1.7

# NOTE: 'Checkout submodules' will fail. The project is no longer maintained!
#       https://github.com/marketplace/actions/checkout-submodules
#       https://github.com/marketplace/actions/checkout-submodules#alternatives

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

name: Manually run Action 'workflow_dispatch'

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
  
  test-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      #- name: Checkout submodules
      #  uses: textbook/git-checkout-submodule-action@master
